### PR TITLE
Remove Travis CI; Long live Delivery!

### PR DESCRIPTION
**Pull request by schisamo**
/cc @chef-cookbooks/engineering-services @oferrigni

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: fa6992de-4d72-4d2a-a425-c39dc496e126 approved by: @schisamo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: fa6992de-4d72-4d2a-a425-c39dc496e126 delivered by: @schisamo

**Pull request merged**
