### PR TITLE
Create a symlink to gcc4.9 on freebsd 9 if it exists

### PR DESCRIPTION
**Pull request by scotthain**
@chef-cookbooks/engineering-services @chef-cookbooks/omnibus-maintainers

### CODE REVIEW

**Comment by schisamo** [comment]
I think we should follow a pattern similar to the one we use for AIX and Solaris. We just munge the `PATH` in `load-omnibus-toolcain.sh` (like we do for AIX/Solaris). This won't quite work on FreeBSD 9 as the GCC 4.9 bin is named `gcc49`. We might be able to accomplish the same thing by creating a `CC` entry in `load-omnibus-toolchain.sh` that points to `/usr/local/bin/gcc49`. You could just do something like this in `_compile.rb`:

```ruby
omnibus_env['CC'] << '/usr/local/bin/gcc49'
```

**Comment by scotthain** [comment]
@schisamo will `omnibus_env['CC']` be respected/used in the environment that omnibus (the framework) runs when you use `with_embedded_path`?

**Comment by schisamo** [comment]
@scotthain So I believe the `CC` environment variable pretty much always supersedes any `gcc` in the `PATH`. This is because `CC` usually defaults to `gcc` (or `cc`) which is obviously resolved in the `PATH`.

We will need to test that theory obviously.

**Comment by scotthain** [comment]
@schisamo testing it right now. How strongly do you feel about not doing the symlink if this fails? It seems like a symlink is a rather obvious (for debugging purposes at least) way of doing it that we also have done in other circumstances (gmake/make for example). I worry that an env variable passed through 3 layers of cookbooks may be impossible to debug if it comes down to it.

**Comment by schisamo** [comment]
@scotthain It's best if we try to funnel all the 'special' tweaks for our build environment into `load-omnibus-toolchain.sh`. When we rely on special symlinks or other wackiness it can be difficult to debug the underlying issue. It also makes upgrades to the underlying base install of a slave hard.

**Comment by scotthain** [comment]
Ok @schisamo after testing I can confirm that `with_embedded_path` does nuke the existing env variables in favor of its own right here: https://github.com/chef/omnibus/blob/master/lib/omnibus/software.rb#L706-L711

I'm a little stumped on how else but a symlink to solve the problem, let me know your thoughts!

**Comment by schisamo** [comment]
@scotthain So we usually call `with_embedded_path` along with an embedded call to `` like this:

```ruby
with_embedded_path(with_standard_compiler_flags)
```

Looking through `Omnibus::Software#with_standard_compiler_flags ` it might make the most sense to just build this into that method...something like:

```ruby
when "freebsd"
  freebsd_flags = {
    "LDFLAGS" => "-L#{install_dir}/embedded/lib",
    "CFLAGS" => "-I#{install_dir}/embedded/include -O2",
  }
  # Prefer a modern GCC on older FreeBSD if it's installed
  if (Ohai['platform_version'].to_i <= 9) && which('gcc49')
    freebsd_flags.merge!(
      "CC" => "gcc49"
      "CXX" => "gcc49++",
    )
  end

  # Clang became the default compiler in FreeBSD 10+
  if Ohai['os_version'].to_i >= 1000024
    freebsd_flags.merge!(
      "CC" => "clang",
      "CXX" => "clang++",
    )
  end
  
  freebsd_flags
```

**Pull request closed without merging**
