### PR TITLE
Bump the version of omnibus-toolchain to 1.1.7

### PR DESCRIPTION
**Pull request by sersut**
/cc: @chef-cookbooks/engineering-services 

This is preparing to get Ruby 2.1.8 that is included in omnibus-toolchain 1.1.7 into our slaves.

### CODE REVIEW

**Comment by schisamo** [comment]
👍  assuming 1.1.7 of omnibus-toolchain (and angry-omnibus-tool-chain) gets promoted to stable before this is merged.

**Comment by jaymalasinha** [comment]
👍

**Comment by scotthain** [comment]
👍

**Comment by yzl** [comment]
👍

**Comment by sersut** [comment]
The only failing instance in Travis is due to a network issue. Restarted it two times to no avail. Merging after getting offline confirm from @scotthain

**Pull request merged**
