### PR TITLE
Bump omnibus-toolchain, remove fakeroot def, fix some paths

### PR DESCRIPTION
**Pull request by scotthain**
@chef-cookbooks/engineering-services 

I will be testing this locally against a RHEL5 and RHEL7 node.

### CODE REVIEW

**Comment by scotthain** [comment]
@chef-cookbooks/omnibus-maintainers

**Comment by schisamo** [comment]
👍  assuming your local testing works out.

**Comment by yzl** [comment]
👍 pending local testing

**Comment by sersut** [comment]
👍

**Comment by scotthain** [comment]
Verified locally on both 5 and 7

**Pull request merged**
