### PR TITLE
Release 5.4.0

### PR DESCRIPTION
**Pull request by robbkidd**
prepare the 5.3.4 release

### CODE REVIEW

**Comment by scotthain** [comment]
@legal90 there's a very strange bug that's being tracked down right now where it fails the first time then succeeds - did you try running `kitchen converge` twice? (not an ideal workaround, but appears to do the trick until we can get a fix out)

**Comment by legal90** [comment]
@scotthain Yes, i did. In chef-cookbooks/windows#553 confirmed that it fails only once, but works fine on the subsequent runs.

But unfortunately, in my case it's not an option. I run it via Chef-Solo provisioner in Packer (https://packer.io) for building AWS AMI, so the whole build fails because of the provisioner error :(

**Comment by scotthain** [comment]
@legal90 ahh that's a bummer, sorry to hear that! I'm hoping we'll get a fix at some point soon, it's a really annoying bug.

**Comment by legal90** [comment]
@scotthain I've found why the subsequent run passes successfully. It happens because `windows_zipfile` is skipped here due to `action :nothing`:
https://github.com/chef-cookbooks/wix/blob/8ba8228e64069d3fc4492eca4b4924df510acee4/recipes/default.rb#L33
So that, the wix archive remains unpacked and `C:\wix` is not created while Chef Client run reports a success. That is crucial because such Omnibus builder node won't work.

If we remove the pre-cached `wix311-binaries.zip` file, then the `remote_file` resource will notify `windows_zipfile` and chef-cookbooks/windows#553 will appear again.
So, the subsequent run doesn't actually fix anything, it just hides the error by following a wrong scenario. 

P.s. Let me know if you should move this discussion somewhere else to avoid an off-topic here.

**Comment by scotthain** [comment]
@legal90 We found that yesterday as well! It should be resolved by https://github.com/chef-cookbooks/windows/pull/555 - try updating your windows cookbook.

@robbkidd since we know this is not an omnibus cookbook specific issue, feel free to continue your release whenever you have the cycles

**Comment by tas50** [comment]
I updated this PR with the additional cleanup I did and bumped things to 5.4.0.

**Pull request merged**
