### PR TITLE
[ES-479] Add Windows support to the `omnibus_build` resource

### PR DESCRIPTION
**Pull request by schisamo**
/cc @chef-cookbooks/engineering-services @chef-cookbooks/omnibus-maintainers @xenolinguist

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by oferrigni** [comment]
:+1:

**Comment by oferrigni** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 3b643bd7-4e81-42e6-9138-062c26792023 approved by: @oferrigni

**Pull request merged**
