### PR TITLE
Set data bag item lookout to a variable in the correct scope

### PR DESCRIPTION
**Pull request by schisamo**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 81e4018c-3438-46a9-9ed2-55bf380a81e4 approved by: @schisamo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 81e4018c-3438-46a9-9ed2-55bf380a81e4 delivered by: @schisamo

**Pull request merged**
