### PR TITLE
[ES-425] create `omnibus_build` resource for executing builds

### PR DESCRIPTION
**Pull request by schisamo**
Take a look at `test/fixtures/cookbooks/omnibus_build/recipes/execute.rb` for example usage.

/cc @chef-cookbooks/engineering-services @oferrigni @chef-cookbooks/omnibus-maintainers

### CODE REVIEW

**Comment by yzl** [comment]
:+1: pending test issues (and I am looking forward to using this as an example to write some chefspec for the languages cookbook)

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by oferrigni** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 71011196-2aa8-4147-a91c-2efa37630c15 approved by: @oferrigni

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 71011196-2aa8-4147-a91c-2efa37630c15 delivered by: @schisamo

**Pull request merged**
