### PR TITLE
Properly load data bag item from Chef Server

### PR DESCRIPTION
**Pull request by schisamo**
The default CCR is taking place in the context of Chef Zero.

/cc @cwebberOps @chefsalim

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by afiune** [comment]
:shipit:

**Comment by schisamo** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 2e1c083b-bc48-4710-b09a-775a48cb02c2 approved by: @schisamo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by afiune** [comment]
@schisamo don't forget to create the correct `item` inside the `data_bag` .. 

That is to have `item['delivered']` up in the chef-server :smile:

**Comment by schisamo** [comment]
@chefsalim No need. If `item['<ENVIRONMENT>']` doesn't exist `encrypted_data_bag_item_for_environment` falls back to `item['default']`:
https://github.com/sethvargo/chef-sugar/blob/master/lib/chef/sugar/data_bag.rb#L86-L92

**Comment by afiune** [comment]
Nice!

*Salim Afiune* — Solutions Engineer

917.716.0448 – afiune@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/afiune>  Twitter <http://www.twitter.com/afiune>

CHEF

      CHEF.IO <http://www.chef.io/>

TM

*chef.io <http://www.chef.io/>*   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 2e1c083b-bc48-4710-b09a-775a48cb02c2 delivered by: @schisamo

**Pull request merged**
