### PR TITLE
Add msys binaries to the omnibus path because we need a lot of them

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
@schisamo @tyler-ball @mwrock This should put all the tools in the omnibus path - it's one of the main issue with the builds.

**Comment by mwrock** [comment]
:+1:

**Comment by tyler-ball** [comment]
👍

**Comment by schisamo** [comment]
👍  I'm going to merge this and will get things released and deployed later today.

**Comment by ksubrama** [comment]
Thank you!

**Pull request merged**
