### PR TITLE
Ensure chef-sugar is loaded before using DataBag helpers

### PR DESCRIPTION
**Pull request by schisamo**
/cc @cwebberOps 

Will fix the following failure: 
https://delivery.chef.co/e/chef/#/organizations/chef-cookbooks/projects/omnibus/changes/a7fda51c-63d7-4b66-8ad5-08671d305014/status/delivered

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 2f436b79-0a12-4aec-a315-2e7f0cabe477 approved by: @schisamo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 2f436b79-0a12-4aec-a315-2e7f0cabe477 delivered by: @schisamo

**Pull request merged**
