### PR TITLE
Bump WiX version

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 59c5fa13-e04d-4a10-9869-ae273ffbac54 approved by: @schisamo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by ksubrama** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 59c5fa13-e04d-4a10-9869-ae273ffbac54 delivered by: @ksubrama

**Pull request merged**
