### PR TITLE
Remove dates from CHANGELOG

### PR DESCRIPTION
**Pull request by schisamo**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 300b1b09-4bcb-4416-847e-186ec0966b92 approved by: @schisamo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by schisamo** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 300b1b09-4bcb-4416-847e-186ec0966b92 delivered by: @schisamo

**Pull request merged**
