### PR TITLE
Allow toolchain channel override

### PR DESCRIPTION
**Pull request by scotthain**
@chef-cookbooks/engineering-services 

Is this the correct ruby idiom? (the to_sym I mean?)

### CODE REVIEW

**Comment by schisamo** [comment]
👍 

Would be nice to add some test coverage to:
https://github.com/chef-cookbooks/omnibus/blob/master/spec/recipes/omnibus-toolchain_spec.rb

**Comment by scotthain** [comment]
Good call @schisamo - done

**Comment by scotthain** [comment]
Oops forgot to @chef-cookbooks/omnibus-maintainers - sorry about that.

**Comment by schisamo** [comment]
:shipit:

**Comment by yzl** [comment]
👍

**Pull request merged**
